### ISSUE TITLE
Implement Intermediary Queue for Transaction Execution Hashes to Ensure Commitment Before Block Propagation

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1085]
# Why:
To ensure the integrity and consistency of the blockchain, it is crucial to verify that all transaction executions have been committed and sent to peers before appending the block to the log and propagating it. This intermediary queue will help track the state of transaction executions and guarantee their commitment before the block is finalized.

# How:
Create an Intermediary Queue:

- [ ] Implement an intermediary queue to store the hashes of transaction executions.
- [ ] Add the intermediary queue to the Consensus struct.
- [ ] Implement necessary methods to manage the queue, including adding, checking, and removing transaction execution hashes.
- [ ] Implement logic to check the commitment of all transaction executions in the intermediary queue before appending the block to the log.
- [ ] Only propagate the block to peers and commit it to the log if all transaction executions have been successfully committed.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
