### ISSUE TITLE
Logsbloom field is zero

### ISSUE THREAD

**Issue by carneiro-cw** [cloudwalk/stratus#1134]
Logsbloom field is zero in responses of `eth_getTransactionReceipt`, and for transactions in array in responses `eth_getBlockByNumber`, `eth_getBlockByHash`. Logsbloom can be used for indexing (for Blockscout for example). This is why it should be present for both - blocks and transactions.

**Comment by arthurmm-cloudwalk** [comment]
from https://cloudwalk.slack.com/archives/C066PLE20AC/p1718381466996999

**Comment by carneiro-cw** [comment]
> and for transactions in array in responses `eth_getBlockByNumber`, `eth_getBlockByHash`
Since substrate also does not return the individual transaction's `LogsBloom` in the transactions array returned by those methods I think this is a non-issue.

As for the issue of `eth_getTransactionReceipt` not returning the correct transaction's `LogsBloom`, ideally we'd fix this when saving the transaction, but this is can only be done once we have data versioning on rocksdb. Until we could compute the logsbloom when returning the receipt every time.
