### ISSUE TITLE
Stratus always adds zeros to the deployed contract bytecode at the end

### ISSUE THREAD

**Issue by carneiro-cw** [cloudwalk/stratus#1135]
Stratus always adds zeros to the deployed contract bytecode at the end. `000000000000000000000000000000000000000000000000000000000000000000`

**Comment by marcospb19-cw** [comment]
It was noted those were added by the EVM.

**Comment by arthurmm-cloudwalk** [comment]
from https://cloudwalk.slack.com/archives/C066PLE20AC/p1718381466996999

**Comment by carneiro-cw** [comment]
I'll close this since this seems to be a non-issue.
