### ISSUE TITLE
Implement Block Appending Logic in Raft Consensus Module

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1221]
# Why:
To ensure the consistency of log entries in the Raft consensus module, it is necessary to validate the prevLogIndex before appending a new block. This validation ensures that logs are appended in the correct order and helps prevent inconsistencies that could arise from mismatched log indices.

# How:

- [ ] Modify the append_block_commit function to include a check for prevLogIndex.
- [ ] Update the log appending logic to handle cases where prevLogIndex matches the current index by appending the new block.
- [ ] Implement error handling for cases where prevLogIndex does not match, possibly rejecting the append or resolving log inconsistencies.
- [ ] Add unit tests to cover different scenarios of block appending, ensuring that the logic works as expected in both matching and non-matching prevLogIndex cases.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
