### ISSUE TITLE
Refactor to Use RocksDB Index instead of Latest Block Commit

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1222]
# Why:
The current management of the latest block commit in the Raft consensus module does not utilize the actual index from RocksDB. Using the RocksDB index will provide a more accurate and reliable way to manage log entries and ensure that the latest block commit is consistently tracked.

# How:

- [ ] Identify all instances in the code where the latest block commit is managed.
- [ ] Replace the current logic with an implementation that uses the actual index from RocksDB.
- [ ] Update the append and retrieval logic to interact with the RocksDB index, ensuring that all operations correctly use this index.
- [ ] Add unit tests to verify that the latest block commit is accurately managed using the RocksDB index, covering scenarios for appending, retrieving, and updating log entries.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
