### ISSUE TITLE
Implement `save_execution` to Process Incoming AppendEntries Requests

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1246]
# Why:
The current implementation lacks a dedicated method to handle the incoming append entries requests for transaction executions. This is crucial for ensuring that the Raft log is correctly updated with new entries from the leader, which is essential for maintaining a consistent and fault-tolerant system.

# How:
1. Create a `save_execution` method in the `AppendLogEntriesStorage` struct.
2. This method should take an index, term, and transaction execution entries.
3. The method should encode and save these entries into RocksDB.
4. Update the appropriate places in the code to call this method when new entries arrive via `AppendEntries` RPC.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
