### ISSUE TITLE
Stop Miner from Auto-Mining on follower-mode

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1247]
# Why:
Currently, the miner is auto-mining blocks, which can lead to inconsistency when running in a Raft cluster. The leader should be the only one to mine new blocks and propagate them to followers.

# How:
1. Add a configuration option to disable auto-mining.
2. Update the miner initialization code to respect this configuration.
3. Ensure that the miner only mines new blocks when explicitly instructed by the leader.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
