### ISSUE TITLE
Disable Data Gathering from Substrate in Sync-Online Mode

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1248]
# Why:
In the current implementation, the system continues to gather data from the substrate when running in sync-online mode. This can lead to data inconsistency and conflicts within the Raft cluster.

# How:
1. Add a check to disable data gathering from the substrate when in sync-online mode.
2. Update the initialization code to ensure this check is in place.
3. Ensure that the system only gathers data when not running in sync-online mode.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
