### ISSUE TITLE
Handle Missing Transaction Hashes in Block Entry

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1250]
# Why:
In the current implementation, blocks are appended with a set of transaction hashes. However, there may be cases where some transaction hashes do not arrive in time for the block to be committed. This discrepancy can lead to incomplete or inconsistent state representations in the blockchain, potentially causing errors in transaction validation, block execution, and consensus mechanisms.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
