### ISSUE TITLE
Standardize error gRPC response format

### ISSUE THREAD

**Issue by gabriel-aranha-cw** [cloudwalk/stratus#1260]
The gRPC endpoints specify Error Status Codes defined in the protobuf definition. However, when actually returning error responses, the status codes are not consistent with the ones defined in the endpoint. Example below.

[AppendBlockCommit error response on not leader](https://github.com/cloudwalk/stratus/blob/main/src/eth/consensus/server.rs#L82-L88):
```
if consensus.is_leader() {
            tracing::error!(sender = request_inner.leader_id, "append_block_commit called on leader node");
            return Err(Status::new(
                (StatusCode::NotLeader as i32).into(),
                "append_block_commit called on leader node".to_string(),
            ));
        }
```

Actual returned error response:
```
ERROR:
  Code: Unknown
  Message: append_block_commit called on leader node
```

[Also confirmed on unit test](https://github.com/cloudwalk/stratus/blob/main/src/eth/consensus/server.rs#L303-L309):
```
        let response = service.append_block_commit(request).await;
        assert!(response.is_err());

        let status = response.unwrap_err();
        assert_eq!(status.code(), tonic::Code::Unknown);
        assert_eq!(status.message(), "append_block_commit called on leader node");
    }
```

The fix is to probably adapt all error responses to use the standard AppendTransactionExecutionsResponse, AppendBlockCommitResponse, RequestVoteResponse formats.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
