### ISSUE TITLE
MetaMask transactions are forever pending

### ISSUE THREAD

**Issue by mayconamaroCW** [cloudwalk/stratus#1261]
The same operation works in Substrate

**Comment by mayconamaroCW** [comment]
The cause was found. [Slack thread](https://cloudwalk.slack.com/archives/CRUDA4JTF/p1719589919607319?thread_ts=1719427359.007439&cid=CRUDA4JTF).

Stratus is re-enconding transactions.

**Comment by carneiro-cw** [comment]
Closed by #1282 and #1280
