### ISSUE TITLE
Handle Poison Messages with Invalid Lengths Arriving at the GRPC Server

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1288]
# Why:
Currently, the server does not have sufficient validation to handle incoming gRPC requests that contain fields with incorrect lengths. This can result in unexpected behavior, including crashes and inconsistent state within the server. By introducing robust validation for all incoming messages, we can ensure that the server gracefully handles malformed or malicious inputs, thereby increasing the overall stability and reliability of the system.

# How:
1. **Input Validation**: Implement comprehensive validation checks for all incoming gRPC requests. This includes verifying the lengths of fields such as hashes, bloom filters, and other binary data to ensure they meet the expected criteria.

2. **Error Handling**: Develop a robust error handling mechanism that identifies and rejects malformed messages before they reach the core processing logic. This involves sending appropriate error responses back to the client, indicating the nature of the validation failure.

3. **Logging and Monitoring**: Enhance logging to capture details of any validation failures, including the source of the request and the specific validation error. Implement monitoring and alerting based on these logs to quickly identify and respond to repeated attempts to send malformed messages.

4. **Unit Tests**: Create unit tests to cover various scenarios of malformed input, ensuring that the validation logic correctly identifies and handles these cases.

5. **Documentation**: Update the server documentation to include information about the new validation checks, error responses, and guidelines for clients to ensure they send well-formed requests.

By implementing these measures, we can significantly reduce the risk of poison messages affecting the stability and integrity of the server.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
