### ISSUE TITLE
Integration Test: Append Transaction Entries and Read on Another Server

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1292]
## Why

We need to ensure the integrity and correctness of the transaction entries across multiple servers in a distributed system. By appending transaction entries on one server and reading them on another, we can verify the consistency and reliability of our consensus and mining mechanisms.

## How

1. **Setup Two Servers**: Initialize two servers in the test environment. Server A will be used to append transaction entries, and Server B will be used to read the appended entries.
   
2. **Append Transaction Entries**: On Server A, create and append a set of transaction entries using the existing append mechanism.
   
3. **Synchronization**: Ensure the synchronization between Server A and Server B using the consensus protocol. This involves making sure that Server B receives and processes the entries appended on Server A.
   
4. **Read Transaction Entries**: On Server B, read the transaction entries that were appended on Server A. Use both the mined data and consensus data to verify the integrity and correctness of the entries.
   
5. **Assertions**: Verify that the transaction entries read on Server B match exactly with those appended on Server A. Include checks for the data integrity and consistency.

6. **Automate the Test**: Ensure that this integration test is automated and can be run as part of the CI/CD pipeline.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
