### ISSUE TITLE
fallback to serial execution when conflict is detected in parallel

### ISSUE THREAD

**Issue by mayconamaroCW** [cloudwalk/stratus#1300]
As suggested by @dinhani-cw:

When a conflict is detected, we should add the transaction to a queue of transactions that will be executed serially in background instead of being retried forever.
It is necessary to create the queue of transactions to be executed serially by a background worker.

https://github.com/cloudwalk/stratus/blob/616d8fa93213710e85c08561e68021b0e0611539/src/eth/executor.rs#L272 

[Context](https://cloudwalk.slack.com/archives/C066PLE20AC/p1719821601930019) (staff only)

**Comment by dinhani-cw** [comment]
Fixed.
