### ISSUE TITLE
Address Conflicts and RocksDB Initialization Failure During Stratus Restart in Chaos Experiment

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1395]
During the chaos experiment involving the restart of Stratus instances, multiple errors were encountered:

1. **Address Conflicts**:
   - **Error**: `failed to create tokio-console server`
     - **Reason**: `Address already in use`
     - **Address**: `0.0.0.0:6670`
   - **Error**: `failed to create metrics exporter`
     - **Reason**: `Address already in use`
     - **Address**: `0.0.0.0:9002`

2. **RocksDB Initialization Error**:
   - **Error**: `Failed to open RocksDB, trying to repair it to open again...`
     - **Reason**: `Resource temporarily unavailable`
     - **Path**: `tmp_rocks_3002-rocksdb`

### Steps to Reproduce
1. Ensure no other instances of Stratus or other applications are using the addresses `0.0.0.0:6670` and `0.0.0.0:9002`.
2. Run the chaos experiment with:
   ```sh
   just run-chaos-experiment stratus 3 3 false
   ```

**Comment by dinhani-cw** [comment]
Raft is not going to be implemented soon.
We should review all Raft tasks if it is coming back.
