### ISSUE TITLE
Refactor Duplicated Error Handling Code in Append Transaction Executions Response

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1400]
# Why
The current implementation contains repetitive code patterns for handling errors and generating responses in the AppendTransactionExecutionsResponse. This duplication makes the code harder to maintain, more error-prone, and less readable. By refactoring, we can improve code quality, maintainability, and readability.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
