### ISSUE TITLE
Implement Client-side Handling for Error Responses in Append Transaction Executions

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1401]
# Why
Currently, the client-side implementation does not adequately handle various error responses from the AppendTransactionExecutionsResponse. This can lead to incomplete or failed operations without proper feedback to the user. Implementing comprehensive error handling on the client side will ensure better user experience and robustness of the client application.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
