### ISSUE TITLE
Implement Tests to Read Balance and Block Details to Verify Proper Transaction Storage

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1440]
# Why
Ensuring that all transactions are properly stored and reflected in the balance and block details is crucial for the integrity and reliability of the Stratus system. These tests will help detect any discrepancies in transaction storage, which can indicate underlying issues in the consensus mechanism or storage backend.

# How
1. **Read Balance Test**:
   - Implement a test that reads the balance of accounts after a series of transactions.
   - Verify that the balances reflect all executed transactions accurately.
   
2. **Read Block Details Test**:
   - Implement a test to read block details, including transactions, from the blockchain.
   - Verify that all transactions are present and correctly stored within the blocks.
   
3. **Test Suite Integration**:
   - Integrate these tests into the existing test suite to run automatically.
   - Ensure the tests cover various scenarios, including high transaction volumes and edge cases.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
