### ISSUE TITLE
Implement Load Balancer Test for Consistent Request Distribution and Result Verification

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1441]
# Why
Testing the load balancer is essential to ensure that requests are evenly distributed across consensus servers and that all servers provide consistent results. This helps in maintaining the reliability and performance of the distributed system under load.

# How
1. **Setup Load Balancer**:
   - Configure a load balancer to distribute requests across multiple consensus servers.
   
2. **Request Distribution Test**:
   - Implement a test that sends a high volume of requests through the load balancer.
   - Verify that the requests are evenly distributed among the consensus servers.
   
3. **Result Consistency Test**:
   - Ensure that all consensus servers return the same results for the same requests.
   - Compare the responses from different servers to check for consistency.
   
4. **Test Suite Integration**:
   - Integrate these tests into the existing test suite to run automatically.
   - Monit

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
