### ISSUE TITLE
Implement Tests to Restart Servers During Balance and RawTransactions Reads to Verify Raft Request Distribution

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1442]
# Why
Testing the system’s behavior during server restarts is crucial to ensure that requests are properly distributed and handled by the Raft consensus algorithm. This helps in verifying the system’s fault tolerance and robustness.

# How
1. **Read Balance and RawTransactions Test**:
   - Implement tests to read account balances and raw transactions while the system is under load.
   
2. **Server Restart Scenario**:
   - Implement a test that restarts one or more servers during the read operations.
   - Ensure that the Raft consensus algorithm properly distributes the requests to other available servers.
   
3. **Verify Request Handling**:
   - Verify that the restarted servers correctly rejoin the Raft cluster and resume handling requests without data loss or corruption.
   
4. **Test Suite Integration**:
   - Integrate these tests into the existing test suite to run automatically.
   - Ensure the tests cover various scenarios, including partial and full cluster restarts.

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
