### ISSUE TITLE
Consensus Election on 3 instances sometimes not stabilizing on a Leader.

### ISSUE THREAD

**Issue by gabriel-aranha-cw** [cloudwalk/stratus#1444]
When running consensus on 3 instances, sometimes the third instance will begin a infinite request election loop, suggesting there might be a bug in the election logic.

How to reproduce:
Run the command below a few times.
`just run-chaos-experiment stratus 3 1 false leader-election`

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
