### ISSUE TITLE
Consensus peer state not being persisted on transaction execution flow

### ISSUE THREAD

**Issue by gabriel-aranha-cw** [cloudwalk/stratus#1446]
The peer state of `next_index` and `match_index` when calling [append_entry_to_peer](https://github.com/cloudwalk/stratus/blob/main/src/eth/consensus/mod.rs#L505-L510) on transaction execution flow is always set to zero. This is causing unnecessary overwriting and retrying of old entries due to the state not being consistent.

How to reproduce:
Add the debug log line below in this [part](https://github.com/cloudwalk/stratus/blob/main/src/eth/consensus/mod.rs#L505-L510):
`tracing::info!(peer_clone.next_index, peer_clone.match_index, "sending transaction executions to peer");`

**Comment by carneiro-cw** [comment]
We've shelved raft for now, closing.
