### ISSUE TITLE
[FEAT] Implement BlockchainClient

### ISSUE THREAD

**Issue by dinhani-cw** [cloudwalk/stratus#145]
We need to support calling at least a few RPC methods to import blocks from other blockchains.

* eth_blockNumber
* eth_getBlockByNumber
* eth_getTransactionReceipt
* eth_getStorageAt

Ideally the implementation should return a `serde_json::Value` because we cannot guarantee that different blockchains RPC endpoints will have the same struct.

We can have different implementations that returns a more strict struct if necessary, but the primary case is for dynamic return types.

**Comment by renancloudwalk** [comment]
done
