### ISSUE TITLE
[FEAT] Create read_account_opt and read_slot_opt

### ISSUE THREAD

**Issue by dinhani-cw** [cloudwalk/stratus#146]
`read_account` and `read_slot` returns the default value when a value is not found in the storage.

New versions suffixed with `_opt` should be added. These new versions will return an `Option` instead of the default value.

The existent versions will become default implementations in the `EthStorage` trait and delegate the call to `Option` version.

This change has 2 benefits:
* Remove the logic to return value that is currently duplicated in the `InMemoryStorage` and `PostgresStorage`.
* Allow `MixedStorage` to call the permanent storage instead of the temporary storage when a value is not found instead of assuming the default value.

**Comment by arthur-cw** [comment]
closed by https://github.com/cloudwalk/stratus/pull/173
