### ISSUE TITLE
Remove Dead Code and Unused Imports in Consensus Modules

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#1499]
### Why
Dead code and unused imports can lead to several issues in the codebase:

Maintainability: Dead code and unused imports clutter the codebase, making it harder to maintain and understand.
Performance: Although the performance impact is generally minimal, it can affect the build time and resource usage during compilation.
Code Quality: Having dead code and unused imports is a sign of poor code quality and can hide potential bugs or issues.
Readability: Clean code is easier to read and understand. Removing unnecessary code improves the readability of the codebase.

**Comment by marcospb19-cw** [comment]
I can't find the consensus module anymore on Stratus, does this still apply?
