### ISSUE TITLE
Remove unnecessary binaries and create importer-online component

### ISSUE THREAD

**Issue by arthurmm-cloudwalk** [cloudwalk/stratus#1531]

**Comment by gabriel-aranha-cw** [comment]
Unnecessary binaries and code removal PRs:
https://github.com/cloudwalk/stratus/pull/1520
https://github.com/cloudwalk/stratus/pull/1517

**Comment by gabriel-aranha-cw** [comment]
Importer as component:
https://github.com/cloudwalk/stratus/pull/1584
