### ISSUE TITLE
Implement Ethereum JSON-RPC Filter Methods

### ISSUE THREAD

**Issue by mayconamaroCW** [cloudwalk/stratus#311]
Implement some or all of the following methods

- [eth_newFilter](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_newfilter)
- [eth_newBlockFilter](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_newblockfilter)
- [eth_newPendingTransactionFilter](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_newpendingtransactionfilter)
- [eth_uninstallFilter](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_uninstallfilter)
- [eth_getFilterChanges](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getfilterchanges)
- [eth_getFilterLogs](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getfilterlogs)

**Comment by dinhani-cw** [comment]
Still pending implementation.

**Comment by dinhani-cw** [comment]
Closing this because no one is missing these methods.
If we want full JSON-RPC compatibilty, we re-open the issue.
