### ISSUE TITLE
Reject transactions without chain id or save them null

### ISSUE THREAD

**Issue by mayconamaroCW** [cloudwalk/stratus#315]
Currently we're automatically considering defaults. It could easily lead to inconsistencies.

Either save it null or reject the transaction.

~Also, we mention both Testnet and Mainnet chain id in the code. It would be better to isolate these values by environment.~

**Comment by dinhani-cw** [comment]
We are not considering defaults anymore and the transaction will fail in the EVM execution. It will be saved as null. This behavior seems to be good enough.
