### ISSUE TITLE
Suggestion: Make the lifetime of PermanentStorage 'static

### ISSUE THREAD

**Issue by carneiro-cw** [cloudwalk/stratus#489]
Since each storage is started when the stratus starts, and is only dropped when stratus stops, it would make sense for their lifetime to be 'static. This would enable us to use less `Arc`s (for instance when spawning threads/tasks).

**Comment by dinhani-cw** [comment]
I tried to refactor StratusStorage to be static, but it will require all services to be static, so it is a big refactoring of the codebase.
I will close it for now because it is not critical. Arc is enough for now.
