### ISSUE TITLE
Reaching out...

### ISSUE THREAD

**Issue by flanaganplur** [cloudwalk/stratus#59]
A friend sent me [this LinkedIn post](https://www.linkedin.com/posts/luisbebop_github-cloudwalkstratus-evm-executor-activity-7150843396201385984-D-Q1/), saying CloudWalk is also looking to fill some non-technical roles – I have experience as a business editor and writer, and think I could be of some help in the content strategy and messaging department(s). Would love to discuss more. You can [find my LinkedIn profile here](https://www.linkedin.com/in/andrew-f-61040524/) or reach me at andrew@bapho.fun – cheers!

**Comment by arthurmm-cloudwalk** [comment]
Hey @flanaganplur , thanks for the interest in the project.
Unfortunately we don't have positions for Ledger with that capabilities yet, and we don't have forecast in the short term.
By the way, you can view our current open positions through https://jobs.lever.co/cloudwalk.
Actually we are searching for developers interested in the idea of this project.
Perhaps in the future we from ledger team will have positions more related.
