### ISSUE TITLE
Mismatched fields between Stratus and Frontier

### ISSUE THREAD

**Issue by carneiro-cw** [cloudwalk/stratus#729]
When comparing the block header, transactions, and transactions receipts using `utils/compare_block` I've found the following mismatches.
Fields returned by Stratus and NOT by Frontier:
```
Block Header:
  baseFeePerGas
  mixHash
  sealFields
```

Fields returned by Frontier and NOT by Stratus:
```
Block Header:
  author
Transaction:
  accessList
  creates
  publicKey
  raw
  standardV
  type
Receipt:
  effectiveGasPrice
```

Also the fields `miner`, `gasLimit`, `receiptsRoot`, `logsBloom`, `stateRoot` and `cumulativeGasUsed` are always mismatches.

**Comment by dinhani-cw** [comment]
Frontier/Substrate is dead, so I will close this for now.
Some fields are still mocked or using constants, but no one is complaining.
We should also use a new baseline to determine if they are correct like Hive tests or Hardhat.
