### ISSUE TITLE
 Ensure Consistent Transaction Propagation

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#745]
# Why: 

Ensuring that all transactions are uniformly distributed and known across all nodes is vital for maintaining a consistent state of the blockchain's mempool. This uniformity is crucial because discrepancies can arise due to network latency or node failures, leading to potential conflicts or inconsistencies when transactions are selected for block inclusion. Using Raft's log replication ensures that all nodes in the network see the same set of transactions in the same order, which is essential for deterministic blockchain operation.

# How: 

To implement this, every transaction that a node receives should be entered into the Raft log. This log entry then triggers the Raft consensus mechanism, which ensures that the transaction is replicated across all nodes in the network. This replication process includes handling failures and ensuring that even if some nodes go down, they can catch up with the rest of the network once they recover. This approach leverages Raft's strong consistency guarantee, which is crucial for operations where the order and acknowledgement of transactions are critical.

**Comment by dinhani-cw** [comment]
Raft is not going to be implemented soon.
We should review all Raft tasks if it coming back.
