### ISSUE TITLE
Implement Block Propagation to Maintain Order and Consistency

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#746]
# Why: 

In blockchain systems, the integrity of block content across all nodes is fundamental. Any inconsistency in block data or the order of transactions within blocks can lead to forks or validation failures during consensus. Implementing Raft for block creation mitigates this risk by using its consensus mechanism to agree on the exact set of transactions that make up a block and their order, thereby ensuring network-wide consistency.

# How: 

When a block is proposed by the leader node, it should be treated as a new entry in the Raft log. This process starts with the leader collecting transactions from its mempool (organized according to a pre-determined logic, like fee size or arrival time), forming a block, and then broadcasting this block as a log entry to be replicated to the follower nodes. Followers then validate and apply this block to their local blockchain replica upon achieving consensus, ensuring that all nodes have identical copies of the blockchain ledger.

**Comment by dinhani-cw** [comment]
Raft is not going to be implemented soon.
We should review all Raft tasks if it coming back.
