### ISSUE TITLE
Handle Transactions Left Behind in Mempool

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#747]
# Why: 

Transactions that remain too long in the mempool without being included in a block can lead to several issues: reduced transaction throughput, potential transaction expiry, and user dissatisfaction due to long wait times. Additionally, these lingering transactions could eventually be dropped, leading to failed transactions despite users having paid fees.

# How: 

Adjusting the transaction selection criteria to prioritize older transactions can help mitigate this. This can be implemented by modifying the transaction picking algorithm to check the age of transactions in the mempool and prioritize those that are nearing a maximum age limit. Furthermore, regular synchronization of the mempool state across nodes ensures all transactions are known to all nodes and can be included in the blocks being proposed by any leader, thus preventing transactions from being left behind due to node-specific issues.

**Comment by dinhani-cw** [comment]
Raft is not going to be implemented soon.
We should review all Raft tasks if it coming back.
