### ISSUE TITLE
Make `Account.code_hash` Optional

### ISSUE THREAD

**Issue by carneiro-cw** [cloudwalk/stratus#753]
Currently the code_hash for an account without bytecode is the Keccak256 hash of an empty string (`0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`), we could make it optional since most accounts don't have bytecode.

**Comment by dinhani-cw** [comment]
CodeHash can just be entirely removed, there is no use for it, so I will open an new issue for that and close this one.
