### ISSUE TITLE
 Implement Basic Chaos Testing in Development Environment

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#883]
# Why:

To ensure that the application can handle unexpected failures and recover gracefully, it is essential to simulate failure scenarios such as pod crashes during the development phase. This will help identify and fix resilience issues early in the development lifecycle.

**Comment by dinhani-cw** [comment]
Raft is not going to be implemented soon.
We should review all Raft tasks if it is coming back.
