### ISSUE TITLE
Integrate Chaos Testing into CI/CD Pipeline

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#884]
Integrating chaos testing into the CI/CD pipeline ensures that resilience checks are automatically performed on every code change. This helps catch potential issues before they reach production, maintaining system stability and reliability.

**Comment by dinhani-cw** [comment]
Chaos testing seems to be useful only for Raft.
Raft is not going to be implemented soon.
We should review all Raft tasks if it is coming back.
