### ISSUE TITLE
Implement Comprehensive Chaos Testing in Staging Environment

### ISSUE THREAD

**Issue by renancloudwalk** [cloudwalk/stratus#885]
# Why: 
Before deploying to production, it is crucial to perform comprehensive chaos testing in a staging environment that closely resembles the production setup. This ensures that the system is resilient to failures and behaves as expected under stress conditions.

**Comment by dinhani-cw** [comment]
Raft is not going to be implemented soon.
We should review all Raft tasks if it is coming back.
